# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: CONF="stack-8.2.yaml"
    compiler: ": #stack ghc-8.2.2"

  - env: CONF="stack-8.4.yaml"
    compiler: ": #stack ghc-8.4.3"

  - env: CONF="stack-8.6.yaml"
    compiler: ": #stack ghc-8.6.5"

  - env: CONF="stack-8.8.yaml"
    compiler: ": #stack ghc-8.8.3"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

# Get the list of packages from the stack.yaml file
- PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')
- stack --no-terminal --stack-yaml $CONF install doctest

install:
- stack --no-terminal --stack-yaml $CONF build --only-dependencies

script:
- stack --no-terminal --stack-yaml $CONF test --bench --no-run-benchmarks --haddock --no-haddock-deps
- stack --no-terminal --stack-yaml $CONF exec -- doctest src/Language/SexpGrammar/*.hs

notifications:
  email: false
